test: Test.cpp solver.cpp
        /usr/bin/g++ -g Test.cpp solver.cpp -o test
        ./test

demo: Demo.cpp DemoGame.cpp
        /usr/bin/g++ -g Demo.cpp DemoGame.cpp -o demo
        ./demo

clean: 
        rm ./test
        rm ./demo
